# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test-2014LAI.py
# Created on: 2019-04-16 17:49:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


for year in range(2000,2016):
    for j in range(1,365,8):
        globals()['GLASS01B02_V04_A'+str(year)+str(j).zfill(3)+'_2018081_hdf']= "D:\\python\\newLAI\\"+str(year)+"\\GLASS01B02.V04.A"+str(year)+"001.2018081.hdf"

    for mouth in range(12):
        globals()['v'+str(year)+str(mouth).zfill(2)] = "D:\\python\\newLAI\\LAI"+str(year)+"\\"+str(year)+str(mouth).zfill(2)


# Local variables:
GLASS01B02_V04_A2003001_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003001.2018081.hdf"
GLASS01B02_V04_A2003009_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003009.2018081.hdf"
GLASS01B02_V04_A2003017_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003017.2018081.hdf"
GLASS01B02_V04_A2003025_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003025.2018081.hdf"
GLASS01B02_V04_A2003033_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003033.2018081.hdf"
GLASS01B02_V04_A2003041_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003041.2018081.hdf"
GLASS01B02_V04_A2003049_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003049.2018081.hdf"
GLASS01B02_V04_A2003057_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003057.2018081.hdf"
GLASS01B02_V04_A2003065_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003065.2018081.hdf"
GLASS01B02_V04_A2003073_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003073.2018081.hdf"
GLASS01B02_V04_A2003081_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003081.2018081.hdf"
GLASS01B02_V04_A2003089_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003089.2018081.hdf"
GLASS01B02_V04_A2003097_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003097.2018081.hdf"
GLASS01B02_V04_A2003105_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003105.2018081.hdf"
GLASS01B02_V04_A2003113_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003113.2018081.hdf"
GLASS01B02_V04_A2003121_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003121.2018081.hdf"
GLASS01B02_V04_A2003129_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003129.2018081.hdf"
GLASS01B02_V04_A2003137_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003137.2018081.hdf"
GLASS01B02_V04_A2003145_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003145.2018081.hdf"
GLASS01B02_V04_A2003153_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003153.2018081.hdf"
GLASS01B02_V04_A2003161_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003161.2018081.hdf"
GLASS01B02_V04_A2003169_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003169.2018081.hdf"
GLASS01B02_V04_A2003177_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003177.2018081.hdf"
GLASS01B02_V04_A2003185_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003185.2018081.hdf"
GLASS01B02_V04_A2003193_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003193.2018081.hdf"
GLASS01B02_V04_A2003201_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003201.2018081.hdf"
GLASS01B02_V04_A2003209_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003209.2018081.hdf"
GLASS01B02_V04_A2003217_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003217.2018081.hdf"
GLASS01B02_V04_A2003225_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003225.2018081.hdf"
GLASS01B02_V04_A2003233_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003233.2018081.hdf"
GLASS01B02_V04_A2003241_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003241.2018081.hdf"
GLASS01B02_V04_A2003249_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003249.2018081.hdf"
GLASS01B02_V04_A2003257_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003257.2018081.hdf"
GLASS01B02_V04_A2003265_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003265.2018081.hdf"
GLASS01B02_V04_A2003273_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003273.2018081.hdf"
GLASS01B02_V04_A2003281_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003281.2018081.hdf"
GLASS01B02_V04_A2003289_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003289.2018081.hdf"
GLASS01B02_V04_A2003297_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003297.2018081.hdf"
GLASS01B02_V04_A2003305_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003305.2018081.hdf"
GLASS01B02_V04_A2003313_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003313.2018081.hdf"
GLASS01B02_V04_A2003321_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003321.2018081.hdf"
GLASS01B02_V04_A2003329_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003329.2018081.hdf"
GLASS01B02_V04_A2003337_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003337.2018081.hdf"
GLASS01B02_V04_A2003345_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003345.2018081.hdf"
GLASS01B02_V04_A2003353_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003353.2018081.hdf"
GLASS01B02_V04_A2003361_2018081_hdf = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\dat-avhrrLAI\\2003\\GLASS01B02.V04.A2003361.2018081.hdf"
v200301 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200301"
v200302 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200302"
v200303 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200303"
v200304 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200304"
v200305 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200305"
v200306 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200306"
v200307 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200307"
v200308 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200308"
v200309 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200309"
v200310 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200310"
v200311 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200311"
v200312 = "E:\\Zhouyuan\\paper-201811HaihePKU\\dat-Haiherenew20190415\\LAI2003\\200312"


# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003001.2018081.hdf%\"+\"%GLASS01B02.V04.A2003009.2018081.hdf%\"+\"%GLASS01B02.V04.A2003017.2018081.hdf%\"+\"%GLASS01B02.V04.A2003025.2018081.hdf%\")/4", v200301)

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003033.2018081.hdf%\"+\"%GLASS01B02.V04.A2003041.2018081.hdf%\"+\"%GLASS01B02.V04.A2003049.2018081.hdf%\"+\"%GLASS01B02.V04.A2003057.2018081.hdf%\")/4", v200302)

# Process: Raster Calculator (3)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003065.2018081.hdf%\"+\"%GLASS01B02.V04.A2003073.2018081.hdf%\"+\"%GLASS01B02.V04.A2003081.2018081.hdf%\"+\"%GLASS01B02.V04.A2003089.2018081.hdf%\")/4", v200303)

# Process: Raster Calculator (4)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003097.2018081.hdf%\"+\"%GLASS01B02.V04.A2003105.2018081.hdf%\"+\"%GLASS01B02.V04.A2003113.2018081.hdf%\")/3", v200304)

# Process: Raster Calculator (5)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003121.2018081.hdf%\"+\"%GLASS01B02.V04.A2003129.2018081.hdf%\"+\"%GLASS01B02.V04.A2003137.2018081.hdf%\"+\"%GLASS01B02.V04.A2003145.2018081.hdf%\")/4", v200305)

# Process: Raster Calculator (6)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003153.2018081.hdf%\"+\"%GLASS01B02.V04.A2003161.2018081.hdf%\"+\"%GLASS01B02.V04.A2003169.2018081.hdf%\"+\"%GLASS01B02.V04.A2003177.2018081.hdf%\")/4", v200306)

# Process: Raster Calculator (7)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003185.2018081.hdf%\"+\"%GLASS01B02.V04.A2003193.2018081.hdf%\"+\"%GLASS01B02.V04.A2003201.2018081.hdf%\"+\"%GLASS01B02.V04.A2003209.2018081.hdf%\")/4", v200307)

# Process: Raster Calculator (8)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003217.2018081.hdf%\"+\"%GLASS01B02.V04.A2003225.2018081.hdf%\"+\"%GLASS01B02.V04.A2003233.2018081.hdf%\"+\"%GLASS01B02.V04.A2003241.2018081.hdf%\")/4", v200308)

# Process: Raster Calculator (9)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003249.2018081.hdf%\"+\"%GLASS01B02.V04.A2003257.2018081.hdf%\"+\"%GLASS01B02.V04.A2003265.2018081.hdf%\"+\"%GLASS01B02.V04.A2003273.2018081.hdf%\")/4", v200309)

# Process: Raster Calculator (10)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003281.2018081.hdf%\"+\"%GLASS01B02.V04.A2003289.2018081.hdf%\"+\"%GLASS01B02.V04.A2003297.2018081.hdf%\")/3", v200310)

# Process: Raster Calculator (11)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003305.2018081.hdf%\"+\"%GLASS01B02.V04.A2003313.2018081.hdf%\"+\"%GLASS01B02.V04.A2003321.2018081.hdf%\"+\"%GLASS01B02.V04.A2003329.2018081.hdf%\")/4", v200311)

# Process: Raster Calculator (12)
arcpy.gp.RasterCalculator_sa("(\"%GLASS01B02.V04.A2003337.2018081.hdf%\"+\"%GLASS01B02.V04.A2003345.2018081.hdf%\"+\"%GLASS01B02.V04.A2003353.2018081.hdf%\"+\"%GLASS01B02.V04.A2003361.2018081.hdf%\")/4", v200312)

for i in range(12):
    "(\"%GLASS01B02.V04.A"+str(year)+str(i).zfill(3)+".2018081.hdf%\"+\"%GLASS01B02.V04.A2003009.2018081.hdf%\"+\"%GLASS01B02.V04.A2003017.2018081.hdf%\"+\"%GLASS01B02.V04.A2003025.2018081.hdf%\")/4"